// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Bot struct {
	ID        int64
	StudioID  int64
	Token     string
	FirstName string
	Username  string
	CreatedAt time.Time
}

type TelegramUser struct {
	UserID     int64
	TelegramID int64
	Username   sql.NullString
	CreatedAt  time.Time
}
